name: Playground

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
          node-version: 20
      - name: Hello
        run: |
          echo "Hello World!"

        
